package control

import (
	"bytes"
	"errors"
	"fmt"
	"net/url"
	"strconv"
	"strings"
)

type FrpsConfigOptions struct {
	NodeID     string
	ControlURL string
}

type FrpcConfigOptions struct {
	ClientID string
	Mode     string
	Limit    int
	Proxies  []ProxySpec
}

type ProxySpec struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	LocalIP    string `json:"local_ip"`
	LocalPort  int    `json:"local_port"`
	RemotePort int    `json:"remote_port"`
}

func (s *Store) GenerateFrpsConfig(opts FrpsConfigOptions) (string, error) {
	nodeID := sanitizeID(opts.NodeID)
	s.mu.RLock()
	defer s.mu.RUnlock()
	node, ok := s.state.Nodes[nodeID]
	if !ok {
		return "", ErrNodeNotFound
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "bindPort = %d\n", node.BindPort)
	if node.VhostHTTPPort > 0 {
		fmt.Fprintf(&buf, "vhostHTTPPort = %d\n", node.VhostHTTPPort)
	}
	if node.VhostHTTPSPort > 0 {
		fmt.Fprintf(&buf, "vhostHTTPSPort = %d\n", node.VhostHTTPSPort)
	}
	if s.state.Config.AuthToken != "" {
		fmt.Fprintf(&buf, "auth.token = %q\n", s.state.Config.AuthToken)
	}
	fmt.Fprintf(&buf, "webServer.addr = %q\n", "0.0.0.0")
	fmt.Fprintf(&buf, "webServer.port = %d\n", s.state.Config.DashboardPort)
	if opts.ControlURL != "" {
		pluginAddr := strings.TrimRight(opts.ControlURL, "/")
		if parsed, err := url.Parse(pluginAddr); err == nil && parsed.Host != "" {
			if parsed.Scheme == "https" {
				pluginAddr = "https://" + parsed.Host
			} else {
				pluginAddr = parsed.Host
			}
		}
		fmt.Fprintf(&buf, "[[httpPlugins]]\n")
		fmt.Fprintf(&buf, "name = %q\n", "frp-cluster")
		fmt.Fprintf(&buf, "addr = %q\n", pluginAddr)
		fmt.Fprintf(&buf, "path = %q\n", "/api/v1/frp/plugin/"+node.ID)
		fmt.Fprintf(&buf, "ops = [%s]\n", quotedCSV(strings.Split(s.state.Config.PluginOps, ",")))
	}
	return buf.String(), nil
}

func (s *Store) GenerateFrpcConfig(opts FrpcConfigOptions) (string, error) {
	mode := opts.Mode
	if mode == "" {
		mode = ConfigModeAggregate
	}
	clientID := sanitizeID(opts.ClientID)
	if clientID == "" {
		clientID = "client"
	}
	s.mu.RLock()
	nodes, err := s.selectNodesLocked(clientID, mode, opts.Limit)
	s.mu.RUnlock()
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if mode == ConfigModeAggregate {
		fmt.Fprintf(&buf, "# generated by frp-cluster for %s, mode=aggregate\n", clientID)
		fmt.Fprintf(&buf, "# This is a multi-file bundle. Save each marked block as a separate frpc config and run one frpc process per node.\n")
	} else {
		fmt.Fprintf(&buf, "# generated by frp-cluster for %s, mode=%s\n", clientID, mode)
	}
	for i, node := range nodes {
		sectionSuffix := node.ID
		if mode == ConfigModeSingle {
			sectionSuffix = "primary"
		}
		if mode == ConfigModeAggregate || mode == ConfigModeFailover {
			fmt.Fprintf(&buf, "\n# file: frpc-%s-%s.toml\n", clientID, node.ID)
		} else {
			fmt.Fprintf(&buf, "\n# node: %s (%s)\n", node.ID, node.PublicAddr)
		}
		buf.WriteString(renderFrpcNodeConfig(s.state.Config.AuthToken, clientID, sectionSuffix, node, normalizeProxySpecs(opts.Proxies, clientID, sectionSuffix, 20000+i)))
		if mode == ConfigModeSingle {
			break
		}
	}
	return buf.String(), nil
}

func (s *Store) GenerateFrpcConfigFiles(opts FrpcConfigOptions) (map[string]string, error) {
	mode := opts.Mode
	if mode == "" {
		mode = ConfigModeAggregate
	}
	clientID := sanitizeID(opts.ClientID)
	if clientID == "" {
		clientID = "client"
	}
	s.mu.RLock()
	nodes, err := s.selectNodesLocked(clientID, mode, opts.Limit)
	s.mu.RUnlock()
	if err != nil {
		return nil, err
	}
	files := map[string]string{}
	for i, node := range nodes {
		sectionSuffix := node.ID
		name := fmt.Sprintf("frpc-%s-%s.toml", clientID, node.ID)
		if mode == ConfigModeSingle {
			sectionSuffix = "primary"
			name = fmt.Sprintf("frpc-%s.toml", clientID)
		}
		files[name] = renderFrpcNodeConfig(s.state.Config.AuthToken, clientID, sectionSuffix, node, normalizeProxySpecs(opts.Proxies, clientID, sectionSuffix, 20000+i))
		if mode == ConfigModeSingle {
			break
		}
	}
	return files, nil
}

func renderFrpcNodeConfig(authToken, clientID, sectionSuffix string, node ServerNode, proxies []ProxySpec) string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "serverAddr = %q\n", node.PublicAddr)
	fmt.Fprintf(&buf, "serverPort = %d\n", node.BindPort)
	if authToken != "" {
		fmt.Fprintf(&buf, "auth.token = %q\n", authToken)
	}
	fmt.Fprintf(&buf, "user = %q\n", clientID)
	fmt.Fprintf(&buf, "metadatas.client_id = %q\n", clientID)
	fmt.Fprintf(&buf, "metadatas.cluster_node = %q\n", node.ID)
	for _, proxy := range proxies {
		fmt.Fprintf(&buf, "\n[[proxies]]\n")
		fmt.Fprintf(&buf, "name = %q\n", proxy.Name)
		fmt.Fprintf(&buf, "type = %q\n", proxy.Type)
		fmt.Fprintf(&buf, "localIP = %q\n", proxy.LocalIP)
		fmt.Fprintf(&buf, "localPort = %d\n", proxy.LocalPort)
		if proxy.RemotePort > 0 {
			fmt.Fprintf(&buf, "remotePort = %d\n", proxy.RemotePort)
		}
	}
	return buf.String()
}

func ParseProxySpec(value string) (ProxySpec, error) {
	parts := strings.Split(value, ":")
	if len(parts) != 5 {
		return ProxySpec{}, errors.New("proxy must use name:type:localIP:localPort:remotePort")
	}
	localPort, err := strconv.Atoi(parts[3])
	if err != nil || localPort <= 0 {
		return ProxySpec{}, errors.New("invalid proxy localPort")
	}
	remotePort, err := strconv.Atoi(parts[4])
	if err != nil || remotePort <= 0 {
		return ProxySpec{}, errors.New("invalid proxy remotePort")
	}
	spec := ProxySpec{
		Name:       sanitizeID(parts[0]),
		Type:       strings.TrimSpace(strings.ToLower(parts[1])),
		LocalIP:    strings.TrimSpace(parts[2]),
		LocalPort:  localPort,
		RemotePort: remotePort,
	}
	if spec.Name == "" || spec.Type == "" || spec.LocalIP == "" {
		return ProxySpec{}, errors.New("proxy name, type and localIP are required")
	}
	return spec, nil
}

func normalizeProxySpecs(specs []ProxySpec, clientID, sectionSuffix string, fallbackRemotePort int) []ProxySpec {
	if len(specs) == 0 {
		return []ProxySpec{{
			Name:       fmt.Sprintf("%s-health-%s", clientID, sectionSuffix),
			Type:       "tcp",
			LocalIP:    "127.0.0.1",
			LocalPort:  22,
			RemotePort: fallbackRemotePort,
		}}
	}
	out := make([]ProxySpec, 0, len(specs))
	for _, spec := range specs {
		spec.Name = sanitizeID(spec.Name)
		if spec.Name == "" {
			spec.Name = fmt.Sprintf("%s-proxy-%d", clientID, len(out)+1)
		}
		if spec.Type == "" {
			spec.Type = "tcp"
		}
		spec.Type = strings.ToLower(strings.TrimSpace(spec.Type))
		if spec.LocalIP == "" {
			spec.LocalIP = "127.0.0.1"
		}
		out = append(out, spec)
	}
	return out
}

func quotedCSV(values []string) string {
	cleaned := cleanList(values)
	parts := make([]string, 0, len(cleaned))
	for _, value := range cleaned {
		parts = append(parts, fmt.Sprintf("%q", strings.TrimSpace(value)))
	}
	return strings.Join(parts, ", ")
}
